{% set name = "conda-forge-feedstock-ops" %}
{% set version = "0.15.0" %}
{% set python_min = "3.11" %} 

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/conda-forge-feedstock-ops/archive/refs/tags/{{ version }}.tar.gz
  sha256: 187d680026143bca1a374c221af1a3ce75948ffe31c2af0f005c99c8a2904cd5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - conda-forge-feedstock-ops-container = conda_forge_feedstock_ops.__main__:main_container

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - boltons >=23.0.0
    - click
    - conda
    - conda-build >=3.27
    - conda-forge-metadata >=0.11.0
    - conda-package-handling
    - conda-smithy >=3.40.1
    - orjson
    - pixi
    - py-rattler >=0.21.0,<0.22a0
    - pydantic-settings >=2.8.1,<3.0.0
    - python >={{ python_min }}
    - rattler-build-conda-compat >=0.0.2,<2.0.0a0
    - requests
    - ruamel.yaml
    - ruamel.yaml.jinja2
    - wurlitzer
    - zstandard

test:
  imports:
    - conda_forge_feedstock_ops
    - conda_forge_feedstock_ops.check_solvable
  requires:
    - python {{ python_min }}
  commands:
    # fails due to pixi
    # - pip check
    - python -c "import conda_forge_feedstock_ops; assert conda_forge_feedstock_ops.__version__ == '{{ version }}'"
    - conda-forge-feedstock-ops-container --help

about:
  home: https://github.com/regro/conda-forge-feedstock-ops
  summary: 'A package of containerized feedstock maintenance operations'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
